export { default as basicShader } from './basic.glsl';
export { default as lightShader } from './light.glsl';
export { default as mergeShader } from './merge.glsl';
export { default as paletteShader } from './palette.glsl';
export { default as paletteDepthShader } from './palette-depth.glsl';
export { default as paletteLayersShader } from './palette-layers.glsl';
export { default as paletteLayersInstancedShader } from './palette-layers-instanced.glsl';
export { default as spriteShader } from './sprite.glsl';
export { default as sprite2SHader } from './sprite2.glsl';
