
import {
	faAmilia,
	faAndroid,
	faApple,
	faChrome,
	faDeviantart,
	faDiscord,
	faEdge,
	faFacebook,
	faFirefox,
	faGithub,
	faGoogle,
	faInternetExplorer,
	faLinux,
	faOpera,
	faPatreon,
	faSafari,
	faTumblr,
	faTwitter,
	faVk,
	faWindows,
	faYandexInternational,
} from '@fortawesome/free-brands-svg-icons';
import {
	faAngleDoubleDown,
	faAngleDoubleLeft,
	faAngleDoubleRight,
	faAngleDoubleUp,
	faArrowDown,
	faArrowLeft,
	faArrowRight,
	faArrowUp,
	faBan,
	faBell,
	faCalendar,
	faCaretSquareDown,
	faCaretSquareUp,
	faCaretUp,
	faCertificate,
	faChartPie,
	faCheck,
	faCheckCircle,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faChevronUp,
	faCircle,
	faClipboard,
	faClock,
	faClone,
	faCode,
	faCog,
	faCogs,
	faComment,
	faComments,
	faCommentSlash,
	faCompressArrowsAlt,
	faCopy,
	faCrosshairs,
	faCrown,
	faDatabase,
	faDesktop,
	faDownload,
	faDrawPolygon,
	faEdit,
	faEllipsisV,
	faEnvelope,
	faEraser,
	faExchangeAlt,
	faExclamationCircle,
	faEyeDropper,
	faEyeSlash,
	faFile,
	faFileAlt,
	faFileImage,
	faFilter,
	faFlag,
	faFolderOpen,
	faFont,
	faGamepad,
	faGlobe,
	faHashtag,
	faHdd,
	faHeart,
	faHome,
	faHorseHead,
	faIdBadge,
	faImage,
	faInfo,
	faInfoCircle,
	faLanguage,
	faLaughBeam,
	faLock,
	faMapMarkerAlt,
	faMicrochip,
	faMicrophoneSlash,
	faMinus,
	faMinusCircle,
	faMobile,
	faPaintBrush,
	faPause,
	faPlay,
	faPlug,
	faPlus,
	faPlusCircle,
	faQuestionCircle,
	faRedo,
	faRetweet,
	faSave,
	faSearch,
	faShare,
	faSignOutAlt,
	faSlidersH,
	faSpinner,
	faStar,
	faStepForward,
	faStickyNote,
	faStop,
	faSync,
	faTablet,
	faTerminal,
	faTimes,
	faTrash,
	faTv,
	faUpload,
	faUser,
	faUserCog,
	faUserFriends,
	faUserMinus,
	faUserPlus,
	faUsers,
	faUserSecret,
	faUserTimes,
	faVolumeDown,
	faVolumeOff,
	faVolumeUp,
	faWrench,
} from '@fortawesome/free-solid-svg-icons';

export {
	faAngleDoubleDown,
	faAngleDoubleLeft,
	faAngleDoubleRight,
	faAngleDoubleUp,
	faApple,
	faArrowDown,
	faArrowLeft,
	faArrowRight,
	faArrowUp,
	faBan,
	faBell,
	faCalendar,
	faCaretSquareDown,
	faCaretSquareUp,
	faCaretUp,
	faCertificate,
	faChartPie,
	faCheck,
	faCheckCircle,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faChevronUp,
	faCircle,
	faClipboard,
	faClock,
	faClone,
	faCode,
	faCog,
	faCogs,
	faComment,
	faComments,
	faCommentSlash,
	faCompressArrowsAlt,
	faCopy,
	faCrosshairs,
	faDatabase,
	faDesktop,
	faDeviantart,
	faDiscord,
	faDownload,
	faDrawPolygon,
	faEdit,
	faEllipsisV,
	faEnvelope,
	faEraser,
	faExchangeAlt,
	faExclamationCircle,
	faEyeDropper,
	faEyeSlash,
	faFile,
	faFileAlt,
	faFileImage,
	faFilter,
	faFlag,
	faFolderOpen,
	faFont,
	faGamepad,
	faGithub,
	faGlobe,
	faHashtag,
	faHdd,
	faHeart,
	faHome,
	faHorseHead,
	faIdBadge,
	faImage,
	faInfo,
	faInfoCircle,
	faLanguage,
	faLaughBeam,
	faLock,
	faMapMarkerAlt,
	faMicrochip,
	faMicrophoneSlash,
	faMinus,
	faMinusCircle,
	faPaintBrush,
	faPatreon,
	faPause,
	faPlay,
	faPlus,
	faPlusCircle,
	faQuestionCircle,
	faRedo,
	faRetweet,
	faSave,
	faSearch,
	faShare,
	faSignOutAlt,
	faSlidersH,
	faSpinner,
	faStar,
	faStepForward,
	faStickyNote,
	faStop,
	faSync,
	faTerminal,
	faTimes,
	faTrash,
	faTumblr,
	faTwitter,
	faUpload,
	faUser,
	faUserCog,
	faUserFriends,
	faUserMinus,
	faUserPlus,
	faUsers,
	faUserSecret,
	faUserTimes,
	faVolumeDown,
	faVolumeOff,
	faVolumeUp,
	faWrench,
};

export const partyLeaderIcon = faCrown;
export const offlineIcon = faPlug;
export const emptyIcon = {
	prefix: 'fas',
	iconName: 'empty-icon',
	icon: [512, 512, [], 'ffff', ''],
};

export const oauthIcons: { [key: string]: any; } = {
	deviantart: faDeviantart,
	discord: faDiscord,
	facebook: faFacebook,
	github: faGithub,
	google: faGoogle,
	patreon: faPatreon,
	tumblr: faTumblr,
	twitter: faTwitter,
	vkontakte: faVk,
};

export const uaIcons: { [key: string]: any; } = {
	// browser
	'Chrome': faChrome,
	'Chromium': faChrome,
	'IE': faInternetExplorer,
	'Edge': faEdge,
	'Android Browser': faAndroid,
	'Firefox': faFirefox,
	'Safari': faSafari,
	'Mobile Safari': faSafari,
	'Opera': faOpera,
	'Opera Mini': faOpera,
	'Amigo': faAmilia,
	'YaBrowser': faYandexInternational,
	// os
	'Windows': faWindows,
	'Windows Phone': faWindows,
	'Android': faAndroid,
	'iOS': faApple,
	'Mac OS': faApple,
	'Arch': faLinux,
	'CentOS': faLinux,
	'Fedora': faLinux,
	'FreeBSD': faLinux,
	'OpenBSD': faLinux,
	'Debian': faLinux,
	'Ubuntu': faLinux,
	'Linux': faLinux,
	'Chromium OS': faChrome,
	'Firefox OS': faFirefox,
	'Playstation': faGamepad,
	'Nintendo': faGamepad,
	// device
	'console': faGamepad,
	'mobile': faMobile,
	'tablet': faTablet,
	'smarttv': faTv,
};
